# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build, Test and Create Container Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build and push image to Docker Hub
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 
        docker build . -f Dockerfile -t altafmehmood/sampleapi:latest
        docker push altafmehmood/sampleapi:latest
    - name: Build and push image to GHCR
      run: |
        docker login -u ${{secrets.GH_USERNAME}} -p ${{secrets.GH_PAT}} ghcr.io
        docker build . -f Dockerfile -t ghcr.io/altafmehmood/sampleapi:latest
        docker push ghcr.io/altafmehmood/sampleapi:latest
